### ISSUE TITLE
MCM v4.0.7 crash on startup with Bannerlord 1.5.4

### ISSUE THREAD

**Issue by superawesome** [Aragas/Bannerlord.MBOptionScreen#75]
I think this is a known crash already, but I don't see it reported here or with much detail in the nexus discussions for the mod, so hopefully this is helpful.

I'm using:
Harmony 2.0.2.27 ("for fixed launcher" build)
Butterlib v1.0.12
UIExtenderEx v1.0.3

Load order is:
BetterExceptionWindow
Harmony
Butterlib
UIExtenderEx
MCM
MCMv4 MCMv3 Integration
MCMv4 ModLib v1/v13 Integration

here is the info from BetterExceptionWindow:

- Reasons
Source: MCMv4.UI.v4.0.7 
The type initializer for 'MCM.UI.Functionality.Injectors.PrefabInjector' threw an exception. 

- Inner exception
Source: 0Harmony 
Value cannot be null. Parameter name: fieldInfo 

- Callstacks
Protip: Use a debugger like dnSpy or Visual studio to trace the source of error, by stepping the program line by line. 

Inner exception callstack: 
   at HarmonyLib.AccessTools.FieldRefAccess[T,F](FieldInfo fieldInfo)
   at MCM.UI.Functionality.Injectors.PrefabInjector..cctor()

Outer exception callstack: 
   at MCM.UI.Functionality.Injectors.PrefabInjector.InjectDocumentAndCreate(String name, XmlDocument doc)
   at MCM.UI.Functionality.Loaders.PrefabsLoader.Inject(BaseResourceHandler resourceInjector)
   at MCM.UI.MCMUISubModule.<>c.b__2_0(Object s, SubscriptionEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Bannerlord.ButterLib.DelayedSubModule.DelayedSubModuleManager.BaseOnBeforeInitialModuleScreenSetAsRootPostfix(MBSubModuleBase __instance)
   at TaleWorlds.MountAndBlade.Module.SetInitialModuleScreenAsRootScreen()
   at TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch1(Module this, Single dt)

**Comment by Aragas** [comment]
Related to #74.
e1.5.4 changed the UI system, we are currently working on porting the whole framework to the beta!

**Comment by superawesome** [comment]
Very nice, thanks for the work you're doing for the community.

For reference, the crash is unchanged if I remove "MCMv4 MCMv3 Integration" and "MCMv4 ModLib v1/v13 Integration" from the load order. But I'm sure you know this by now. :)

**Comment by Aragas** [comment]
We are, but thanks for the reports anyway! We hope to do a release within this week!

**Comment by Aragas** [comment]
Closed. MCMv4.1.0 works with e1.5.4!
